# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift-Offers' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Swift-Offers
  
  pod 'Alamofire', '~> 4.7'
  pod 'Marshal', '~> 1.2'

  target 'Swift-OffersTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Swift-OffersUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
