//
//  OfferDetailsModels.swift
//  Swift-Offers
//
//  Created by Chris Allinson on 2018-07-14.
//  Copyright (c) 2018 Chris Allinson. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum OfferDetails {
    
    // MARK: actions
    
    enum LoadOffer {
        struct Request {
        }
        struct Response {
            var offer: Offer
        }
        struct ViewModel {
            var offer: Offer
        }
    }
}

