//
//  OfferDetailsPresenter.swift
//  Swift-Offers
//
//  Created by Chris Allinson on 2018-07-14.
//  Copyright (c) 2018 Chris Allinson. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


protocol OfferDetailsPresentationLogic {
    func presentOffer(response: OfferDetails.LoadOffer.Response)
}


// MARK: -

class OfferDetailsPresenter {
    
    // MARK: instance variables
    
    weak var viewController: OfferDetailsDisplayLogic?
}


// MARK: -

extension OfferDetailsPresenter: OfferDetailsPresentationLogic {

    // MARK: OfferDetailsPresentationLogic
    
    func presentOffer(response: OfferDetails.LoadOffer.Response) {
        let viewModel = OfferDetails.LoadOffer.ViewModel(
            offer: response.offer
        )
        viewController?.displayOffer(viewModel: viewModel)
    }
}

