//
//  OfferDetailsInteractor.swift
//  Swift-Offers
//
//  Created by Chris Allinson on 2018-07-14.
//  Copyright (c) 2018 Chris Allinson. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


protocol OfferDetailsBusinessLogic {
    func loadOffer(request: OfferDetails.LoadOffer.Request)
}

protocol OfferDetailsDataStore {
    var offer: Offer! { get set }
}


// MARK: -

class OfferDetailsInteractor: OfferDetailsBusinessLogic, OfferDetailsDataStore {
    
    // MARK: instance variables
    
    var presenter: OfferDetailsPresentationLogic?
    
    var offer: Offer!
    
    
    
    // MARK: Do something
    
    func loadOffer(request: OfferDetails.LoadOffer.Request) {
        let response = OfferDetails.LoadOffer.Response(
            offer: self.offer
        )
        presenter?.presentOffer(response: response)
    }
}

