//
//  OffersModels.swift
//  Swift-Offers
//
//  Created by Chris Allinson on 2018-07-13.
//  Copyright (c) 2018 Chris Allinson. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Offers {
    
    // MARK: model
    
    struct SortOptions {
        var sortBy: SortByOption
        var sortAscDesc: SortAscDescOption
    }
    
    // MARK: actions
    
    enum LoadOffers {
        struct Request {
        }
        struct Response {
            var offers: [Offer]?
            var error: OfferError?
        }
        struct ViewModel {
            var offers: [Offer]?
            var error: OfferError?
        }
    }
}

