//
//  OffersWorker.swift
//  Swift-Offers
//
//  Created by Chris Allinson on 2018-07-13.
//  Copyright (c) 2018 Chris Allinson. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


protocol OffersWorkerInput {
    func fetchOffers(completion: (_ offers: [Offer]?, _ error: OfferError?) -> ())
}


// MARK: -

class OffersWorker: OffersWorkerInput {
    
    func fetchOffers(completion: (_ offers: [Offer]?, _ error: OfferError?) -> ()) {
        completion(
            [
                Offer(id: "ABCD", name: "Offer 1", price: 1.99, imageUrl: nil, description: "description description description description description description description description"),
                Offer(id: "EFGH", name: "Offer 2", price: 2.99, imageUrl: nil, description: "description description description description description description description description"),
                Offer(id: "IJKL", name: "Offer 3", price: 3.99, imageUrl: nil, description: "description description description description description description description description"),
                Offer(id: "MNOP", name: "Offer 4", price: 4.99, imageUrl: nil, description: "description description description description description description description description"),
                Offer(id: "QRST", name: "Offer 5", price: 5.99, imageUrl: nil, description: "description description description description description description description description"),
                Offer(id: "UVWX", name: "Offer 6", price: 6.99, imageUrl: nil, description: "description description description description description description description description"),
                Offer(id: "YZAB", name: "Offer 7", price: 7.99, imageUrl: nil, description: "description description description description description description description description"),
                Offer(id: "CDEF", name: "Offer 8", price: 8.99, imageUrl: nil, description: "description description description description description description description description"),
                Offer(id: "GHIJ", name: "Offer 9", price: 9.99, imageUrl: nil, description: "description description description description description description description description"),
                Offer(id: "KLMN", name: "Offer 10", price: 10.99, imageUrl: nil, description: "description description description description description description description description")
            ],
            nil
        )
    }
}
