//
//  OffersRouter.swift
//  Swift-Offers
//
//  Created by Chris Allinson on 2018-07-13.
//  Copyright (c) 2018 Chris Allinson. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit


@objc protocol OffersRoutingLogic {
    func routeToOfferDetails(segue: UIStoryboardSegue?)
}

protocol OffersDataPassing {
    var dataStore: OffersDataStore? { get }
}


// MARK:

class OffersRouter: NSObject, OffersRoutingLogic, OffersDataPassing {
    
    // MARK: instance variables
    
    weak var viewController: OffersViewController?
    var dataStore: OffersDataStore?
    
    
    
    // MARK: routing
    
    func routeToOfferDetails(segue: UIStoryboardSegue?) {
        if let segue = segue {
            let destinationVC = segue.destination as! OfferDetailsViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToOffer(source: dataStore!, destination: &destinationDS)
        } else {
            let storyboard = UIStoryboard(name: "Offer", bundle: nil)
            let destinationVC = storyboard.instantiateViewController(withIdentifier: "OfferDetailsViewController") as! OfferDetailsViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToOffer(source: dataStore!, destination: &destinationDS)
            navigateToOffer(source: viewController!, destination: destinationVC)
        }
    }
    
    
    
    // MARK: navigation
    
    func navigateToOffer(source: OffersViewController, destination: OfferDetailsViewController) {
        source.show(destination, sender: nil)
    }
    
    
    
    // MARK: passing data
    
    func passDataToOffer(source: OffersDataStore, destination: inout OfferDetailsDataStore) {
        if let selectedIndex = viewController?.tableView?.indexPathForSelectedRow?.row {
            destination.offer = source.filteredOffers[selectedIndex]
        }
    }
}
